### ISSUE TITLE
Cjdns not planned ?

### ISSUE THREAD

**Issue by Jorropo** [libp2p/py-libp2p#113]
I saw that Cjdns is not planned, but Cjdns isn't like tor or i2p :
 - tor are not very "ip" compatible, it use some ip proxy protocol, that require a program to implement support of any supported proxy (socks 4/5) (or tor itself). (you have some exception but there are too rarely used to be considerate here)
 - i2p is better cause you can create a fake ip of an other i2p member (example : you can translate somethings.i2p to 127.4.76.243 locally) (you also have proxy option) so even if a program doesn't support proxy, that not a problem. But that require an intervention on the administration page of your router, so that require work for be implemented (create an API client making that for us (or use proxy)).
 - Cjdns ? Emulate a FULL ip network, Cjdns implement all ip option (I'm not sure for anycast).
 But there is more, the way that he implement that, the connection from ip to Cjdns is a TUN interface, so if your program use layer 3 or more and use the kernel routing table (that will probably will the case for py-libp2p), you don't have ANY work for be Cjdns compatible.
 Because any Cjdns address is like any ip address, Cjdns address are a sub section of ip address (0xfc) and all connection to Cjdns are made by an external daemon getting all packet from the TUN interface and do what it must do.

So for me saying : Cjdns not planned is an error, because you don't need to support Cjdns, Cjdns is fully ip compatible.

This is why I ask :
Why saying that ?
Would you someone to write a test for verifying that all ip compatible transport are cjdns compatible (if needed I will :smile: that is quite simple) ?
Or is "supporting" means here supporting Cjdns without any external daemon ?

**Comment by ralexstokes** [comment]
`py-libp2p` should be able to implement various components to be compatible with an instance of the `cjdns` network. feel free to start work on this and open a PR if you feel strongly about it :) my understanding is that this is not a priority for the current maintainers
