### ISSUE TITLE
PEP8 compliance

### ISSUE THREAD

**Issue by JonathanVusich** [libp2p/py-libp2p#132]
In perusing some of the code, I noticed a fair number of camelcase function names. It would be nice to integrate flake8 into the CI process in order to keep code style consistent.

**Comment by zixuanzh** [comment]
@JonathanVusich thanks, I believe the camelcases mostly come from `kademlia` and zaibon fixed most of them in #129. We have excluded that folder in pylint and it will be included again when that PR is merged in.

**Comment by alexh** [comment]
the `kademlia` module is now PEP8 compliant
