### ISSUE TITLE
Wire up and test close()

### ISSUE THREAD

**Issue by zixuanzh** [libp2p/py-libp2p#136]
Currently, we have close() in `tcp.py`, `mplex.py`, `mplex_stream.py`, `net_stream.py` but they are not properly wired up. We want to be able to do the following in `swarm.py`.

- [ ] close_peer(peer_id): close all connections to a given peer
- [ ] tearDown(): close all listeners by calling something like `transport.listener.close()` and close all connections. It should also prevent new connections and/or listeners from being added to the swarm.

We would also want to have test cases on close() in `muxed_stream()`.

**Comment by Jorropo** [comment]
@zixuanzh I'm making this :)

**Comment by stuckinaboot** [comment]
Is a close() call in any of the above classes supposed to alert the node's relevant peers that the node has called close()? I can clarify further if that does not make sense

**Comment by mhchia** [comment]
`mplex_stream.close`, `swarm.`close_peer`, and `swarm.shutdown` are done.
