### ISSUE TITLE
Implement SECIO security upgrade

### ISSUE THREAD

**Issue by zixuanzh** [libp2p/py-libp2p#138]
A security transport upgrade can upgrade a connection to an encrypted and authenticated connection. The default libp2p security transport will be [SECIO](https://github.com/libp2p/go-libp2p-secio). One can start from implementing the security interface as defined [here](https://github.com/libp2p/go-conn-security/blob/master/interface.go) and then implementing SECIO in `secio.py`. `upgrade_security` in `transport/upgrader.py` can then be implemented to enable security upgrade.

As we are currently focusing on PubSub, we will not be implementing SECIO till later.

**Comment by stuckinaboot** [comment]
Security is addressed in #159
