### ISSUE TITLE
Floodsub RPC seqno

### ISSUE THREAD

**Issue by zixuanzh** [libp2p/py-libp2p#142]
As per #141 , `seqno` in RPC message should be a linearly increasing number based on the [spec](https://github.com/libp2p/specs/tree/master/pubsub#the-message) but instead it is currently just a uuid.

**Comment by stuckinaboot** [comment]
My current thought is that the current asyncio queue approach will need to be shifted to be using blocking priority queues, where priority is determined by seqno
