### ISSUE TITLE
Pre-benchmarking requirements

### ISSUE THREAD

**Issue by stuckinaboot** [libp2p/py-libp2p#146]
In order to perform benchmark tests on various network topologies running floodsub, the following must be completed to prevent memory and latency issues (as well as serving as enhancements):
- [ ] change hardcoded timeout in muxed conn to be an argument
- [x] make seqno a 64-bit big endian  int
- [x] make seen messages list in pubsub into an LRU cache
- [x] remove unnecessary print statements, such as in floodsub.py

**Comment by robzajac** [comment]
Working on timeouts. They can be added to the `net_stream` level, both for initiators and receivers of streams.

**Comment by robzajac** [comment]
Demo is over and these points were implemented.
