### ISSUE TITLE
from vs. from_id in RPC

### ISSUE THREAD

**Issue by stuckinaboot** [libp2p/py-libp2p#154]
Following the RPC [precedent](https://github.com/libp2p/go-libp2p-pubsub/blob/master/pb/rpc.proto), all messages should be serialized the same way across libp2p implementations. However, in python, `from` is a reserved word so we use `from_id`. 

- [ ] Investigate if there is a way to get around this

**Comment by ralexstokes** [comment]
i'm pretty sure the field names used in the protobuf file do not affect the serialization, esp. if you given an explicit field ordering -- feel free to let me know if i'm wrong here but otherwise going to close this
