### ISSUE TITLE
Cleanup unnecessary outdated branches

### ISSUE THREAD

**Issue by stuckinaboot** [libp2p/py-libp2p#164]
There are a number of branches lingering around that need to be deleted from remote. We need to determine which are necessary to keep around and which can be deleted.

**Comment by robzajac** [comment]
Cleaned up branches I knew about - @stuckinaboot a few of yours are left, and a handful from @alexh.

**Comment by stuckinaboot** [comment]
Removed some of mine. May leave bee-movie-demo (unless we want to merge into master since it does demo streaming data and delivering that data in a vector clock-like order) and will leave random topology generator
