### ISSUE TITLE
libp2p node interoperability

### ISSUE THREAD

**Issue by stuckinaboot** [libp2p/py-libp2p#169]
In order to test interoperability with other non-Python libp2p nodes, the first spec that should be ensured is that the libp2p open connection and open stream mechanisms interoperate.

In py-libp2p, the following messaging occurs when Node A and Node B open a new connection:

1) A dials B
2) A sends its peer ID to B and B sends its peer ID to A (this is where the Identify protocol would come into place, which still needs to be implemented to support different Identify services)
3) A and B agree on a security transport module
4) A and B agree on a multiplexer

Then, when Node A opens a new stream to Node B, the following messaging occurs in py-libp2p:

1) A sends open stream message to B
2) A and B agree on a particular protocol to use for communication across that stream

All PubSub mechanisms in libp2p rely on the underlying stream communication so imo it would be best to ensure opening connections and streams to non-python nodes works before moving on to testing PubSub’s interoperability

**Comment by mhchia** [comment]
Closed by several issues before, and py-libp2p now can talk with other clients now!
