### ISSUE TITLE
Migrate to ethereum-style linting

### ISSUE THREAD

**Issue by ralexstokes** [libp2p/py-libp2p#173]
Migrate to the linting style used in the `ethereum` python projects, e.g. use of `flake8` in https://github.com/ethereum/trinity.

**Comment by jeamick** [comment]
Hello ,

does this issue is active ? @ralexstokes 

Thanks
Kind regards 
JM

**Comment by ralexstokes** [comment]
yes @jeamick :)

**Comment by mhchia** [comment]
Added flake8, isort, black.
