### ISSUE TITLE
List py-libp2p on libp2p website

### ISSUE THREAD

**Issue by stuckinaboot** [libp2p/py-libp2p#177]
Currently, there is no listing for py-libp2p on the [libp2p website](https://libp2p.io/implementations/). Once #169 is completed, py-libp2p will be interoperable with go-libp2p (and hopefully all other clients) and is in a position to be publicly listed.

- [ ] add py-libp2p to libp2p website

@raulk feel free to adjust this issue if there are more steps necessary to get py-libp2p to a point to be listed on the libp2p website.

**Comment by pacrob** [comment]
It's listed!
