### ISSUE TITLE
Suggest rename various `router` in the code base to avoid confusion

### ISSUE THREAD

**Issue by NIC619** [libp2p/py-libp2p#185]
Suggestion:
* rename router in `kademlia/protocol.py` to routing_table
* rename router in `network/swarm` to routing
* rename router in `pubsub/pubsub.py` to pubsub_router

**Comment by ralexstokes** [comment]
> Suggestion:
> 
>     * rename router in `kademlia/protocol.py` to routing_table
> 
if you are referring to the `router` property of the `KademliaProtocol` class then this seems to make sense.
>     * rename router in `network/swarm` to routing
> 
`router` here seems ok to me.
>     * rename router in `pubsub/pubsub.py` to pubsub_router
`router` seems ok to me here too...

my logic on the last two is that it should generally be clear from context as the `router` property will be accessed on some containing object... by relying on context, we can avoid "stutter" in names

```python
pubsub = Pubsub()
pubsub.router.add_routeable_thing(...)

swarm = Swam()
swarm.router.add_peer(id, maddr)
```

etc.

**Comment by NIC619** [comment]
> my logic on the last two is that it should generally be clear from context as the router property will be accessed on some containing object... by relying on context, we can avoid "stutter" in names

Yeah, I can totally see that now. Was kind of confused when I first dug into the codebase.
Closing it now.
