### ISSUE TITLE
Change usage of type of peer id from string to `peer.ID`

### ISSUE THREAD

**Issue by NIC619** [libp2p/py-libp2p#189]
PeerInfo [stores peer ID as type `peer.ID`](https://github.com/libp2p/py-libp2p/blob/master/libp2p/peer/peerinfo.py#L32-L34) while in other place peer ID is converted to string type, for example:
- https://github.com/libp2p/py-libp2p/blob/master/libp2p/pubsub/gossipsub.py#L117
- https://github.com/libp2p/py-libp2p/blob/master/libp2p/pubsub/gossipsub.py#L131

IMO this creates confusion and makes it hard to maintain. I suggest we use type `peer.ID` as the canonical way to represent peer ID.

**Comment by ralexstokes** [comment]
did #196 address this fully or is there more here?

**Comment by NIC619** [comment]
Yes!
