### ISSUE TITLE
Pubsub: Tasks are spawned but no way to stop them

### ISSUE THREAD

**Issue by mhchia** [libp2p/py-libp2p#193]
Several tasks are spawned in the background in Pubsub.

1. `handle_peer_queue` in `__init__`
https://github.com/libp2p/py-libp2p/blob/f0046fa3e0952b492837a698b1988e05c9821f47/libp2p/pubsub/pubsub.py#L110

2. `continuously_read_stream` in `stream_handler`, every time a new stream is opened from a peer.
https://github.com/libp2p/py-libp2p/blob/f0046fa3e0952b492837a698b1988e05c9821f47/libp2p/pubsub/pubsub.py#L180

3. `continuously_read_stream ` in `handle_peer_queue`, every time a new peer is connected.
https://github.com/libp2p/py-libp2p/blob/f0046fa3e0952b492837a698b1988e05c9821f47/libp2p/pubsub/pubsub.py#L208

Regardless of how the code will change after https://github.com/libp2p/py-libp2p/issues/191 is fixed, we should maintain all spawned tasks, and close them when `Pubsub` is closed or even being garbage-collected.

**Comment by ralexstokes** [comment]
just to update -- ran into this while running the tests

i'd have to dig in deeper to the `asyncio` machinery to see what is going on here -- sounds like we should finish the feature set and then see what we can do here

**Comment by NIC619** [comment]
Related: https://github.com/libp2p/py-libp2p/pull/226#discussion_r310675182

There are a few places where tasks are also untracked: `kademlia/`, `network/swarm.py` and `mplex/mplex.py`.

**Comment by ralexstokes** [comment]
yeah, we should generally be tracking all of the tasks we make so that we can handle cancellation/shutdown properly

**Comment by mhchia** [comment]
closed by #309
