### ISSUE TITLE
Add type `Publickey` and `PrivateKey` to type hint

### ISSUE THREAD

**Issue by NIC619** [libp2p/py-libp2p#201]
#### What's wrong?
Currently RSA is used in generating key pairs and this binds the type of the public/private key in typing to `RsaKey`.
https://github.com/libp2p/py-libp2p/blob/f6e456c96ed62fdd996c75fcaf94c7faf3051184/libp2p/peer/id.py#L69

#### How can it be fixed?
Add `PublicKey` and `PrivateKey` types to type hint

**Comment by ralexstokes** [comment]
See #214. I'd think that it closes this issue. The only step further would be adding type aliases for `bytes` but I'm not sure how helpful that is, esp if we want to keep to the widest interface allowed for this function

**Comment by ralexstokes** [comment]
@NIC619 can we close this given #214?

**Comment by NIC619** [comment]
IIUC signing and verifying signature would still need `PublicKey` and `PrivateKey` type for the input key?
```python
def sign(privkey: PrivateKey, msg: bytes):
    ...
    return privkey.sign(msg_hash)

def validate_signature(pubkey: PublicKey, msg_hash: bytes):
    ...
    return pubkey.verify(msg_hash)
```

**Comment by ralexstokes** [comment]
yeah -- i wasn't understanding the scope of these types, my bad!

check out #240 .

let me know if you see anything else we want to do here, otherwise we can close it!
