### ISSUE TITLE
Deprecate `SimpleSecurityTransport`

### ISSUE THREAD

**Issue by ralexstokes** [libp2p/py-libp2p#211]
The security of this transport seems to depend on a symmetric key shared ahead of time and this class may only exist for testing purposes.

If it isn't used in the wider scope of the `libp2p` project I'd suggest just removing it after we have our `secio` implementation. In the case that it is useful for testing or something, we can move it under our `tests`... the goal here is to not provide a security transport unless it is actually providing secure communication under the security model of a user of this library.

**Comment by ralexstokes** [comment]
If we move ahead with this, depends on #210 .

**Comment by ralexstokes** [comment]
This transport also doesn't provide transport-level security (comms are unencrypted) so I'm definitely +1 on deprecating it

**Comment by mhchia** [comment]
+1 on deprecating `SimpleSecurity`. I think it makes sense that we have `Insecure` and `Secure`(secio) in this stage.
