### ISSUE TITLE
Do not require `make` during linting

### ISSUE THREAD

**Issue by ralexstokes** [libp2p/py-libp2p#215]
Try something like this: https://stackoverflow.com/questions/25818558/use-wildcard-in-tox-command/25823102#25823102

instead of the current method proxying out to `make` to run the linting during CI in `tox`.

**Comment by ralexstokes** [comment]
@carver and @davesque have good suggestions here -- either the prior comment or something using `find`:
```bash
find . -name '*.py' -exec echo '{}' +
```

**Comment by mhchia** [comment]
Could you elaborate more on the reason we use put those linting commands in `Makefile`? I guess it is for convenience?


> @carver and @davesque have good suggestions here -- either the prior comment or something using find:

Good idea! In Makefile, we can just call `$(shell find . -name '*.py' -exec echo '{}' +)`.

**Comment by ralexstokes** [comment]
i started w/ this in `tox.ini`.

```
[testenv:lint]
    # ...
    black --check foo.py bar.py subdir/*.py
```

trying to just capture the python files in `subdir` and ignoring files deeper in the file tree.

It turns out that the `ini` parser doesn't do any glob expansion so `black` received a literal argument `subdir/*.py` which is not a file we have... and misses the files we want.

So in searching for a solution, I found we could call out to `make`. But `make` is a non-uniform dependency so its better to use something we can rely on -- either shelling out in the `ini` file (having bash interpret the line manually) or doing effectively the same thing w/ `find`.

At this point, I'd like to try using `find` -- I'll put a PR together although it does touch the `flake8` stuff so easier if we can get that merged first (but also ok if we don't)
