### ISSUE TITLE
Propose to rename `INetwork.notify`

### ISSUE THREAD

**Issue by NIC619** [libp2p/py-libp2p#219]
What `notify` does: register a notifee to the `Network`(i.e., `Swarm`).
https://github.com/libp2p/py-libp2p/blob/c8005c811330f540bff246838582f886da9ab39f/libp2p/network/swarm.py#L234-L242

Propose to rename it to `new_notifee` or `register_notifee` to avoid confusion. Open to other suggestions.

**Comment by mhchia** [comment]
+1, I'm good with both but prefer `register_notifee` more.

**Comment by ralexstokes** [comment]
yeah given this code, i think `register_notifee` is a more precise name.

**Comment by ralexstokes** [comment]
another question though: does the type checker allow something that is not an `INotifee` to be used w/ this function? if not, then we don't need the `isinstance` check and can remove the boolean indication.

**Comment by NIC619** [comment]
Yeah mypy will catch this and it makes sense to remove the `isinstance` check.
But other code base that use pylibp2p as library will then be able to register a non-`INotifee` type notifee. Though I'm not sure if this type of error is something that we should guard against. Do we need to add an `isinstance` check on every function arguments?🤔

**Comment by mhchia** [comment]
Closed by #305
