### ISSUE TITLE
`Peer.ID` implementation only offers `RSA` right now

### ISSUE THREAD

**Issue by ralexstokes** [libp2p/py-libp2p#222]
The peer identity spec supports several different cryptosystems for identity generation; we should at least make it straightforward to use `secp256k1` keys.

**Comment by ralexstokes** [comment]
https://github.com/libp2p/specs/blob/master/peer-ids/peer-ids.md

**Comment by mhchia** [comment]
Update: we need `secp256k1` for interoperability.
