### ISSUE TITLE
Fix MplexStream

### ISSUE THREAD

**Issue by ChihChengLiang** [libp2p/py-libp2p#227]
1. IMuxedConn has no `conn_lock` defined but referenced.
2. Add proper API to avoid accessing `mplex_conn.buffers`

https://github.com/libp2p/py-libp2p/blob/cb3a59e0acb726faf4c2db9c23496ac519ad5432/libp2p/stream_muxer/mplex/mplex_stream.py#L72-L75

**Comment by mhchia** [comment]
Will there be any problem if we don't use any lock at all?

**Comment by ralexstokes** [comment]
so did we want to do anything here? otherwise, let's close this issue

i haven't looked at this code too closely (but i suspect i will soon as i do some interop testing)... if there are concurrency issues here, it should become clear pretty quickly :)

**Comment by ChihChengLiang** [comment]
I would say safely remove these codes and see what unfolds.

**Comment by mhchia** [comment]
Closed by https://github.com/libp2p/py-libp2p/pull/282.
