### ISSUE TITLE
Add addrs of the peer's `PeerID` to `Peerstore` after being connected

### ISSUE THREAD

**Issue by mhchia** [libp2p/py-libp2p#233]
Currently, if peer A connects peer B, the addrs of B is present in A.peerstore, whereas the addrs of A is not in B.peerstore. IMO B(connection receiver) should store the address of A(connection initiator).

**Comment by ralexstokes** [comment]
agree -- i would spend a few minutes looking at the go implementation just to see what they do here. but it does make sense that a node stores every peer it knows about in the peerstore (inbound or outbound) as it may need them in the future

**Comment by mhchia** [comment]
On second thought, there is probably no way for a peer who is dialed to know the listener address of the dialing peer. I fixed the `new_stream` procedure to use the existing connection, instead of trying to dialing, and there is no issue now.
