### ISSUE TITLE
Change read/write to varint-prefixed

### ISSUE THREAD

**Issue by mhchia** [libp2p/py-libp2p#237]
Messages are sent with varint-prefixed in many places in go-libp2p. However, we didn't do it in py-libp2p.

#### Example
- Python
    - py-libp2p.Pubsub reads/writes data to the stream directly: https://github.com/libp2p/py-libp2p/blob/28f6de37ee22d9ca6b9b97a990c0d1cb3b0019ac/libp2p/pubsub/floodsub.py#L77 
- Go
    - go-libp2p-pubsub uses gogo-protobuf.DelimitedReader/Writer: https://github.com/libp2p/go-libp2p-pubsub/blob/49274b0e8aecdf6cad59d768e5702ff00aa48488/comm.go#L36
    - VarInt-prefixed Read/Write in gogo-protobuf: https://github.com/gogo/protobuf/blob/07eab6a8298cf32fac45cceaac59424f98421bbc/io/varint.go#L109-L126

### TODO
- [ ] Compare the read/write in py-libp2p with Go, find out the ones which should be "varint-prefixed", and add prefixes to the data-to-be-sent in those places.

**Comment by ralexstokes** [comment]
This is part of what I mean in #216. We will want to make clear abstractions for each of these use cases so that we don't end up w/ leaky reads/writes all over the place

**Comment by mhchia** [comment]
- [ ] Add varint-read/write to pubsub
