### ISSUE TITLE
Add delimited read/write

### ISSUE THREAD

**Issue by mhchia** [libp2p/py-libp2p#238]
In the negotiation process in Go, "delimited read/write" is used. However, we read/write raw bytes here.

Functions are implemented here: https://github.com/libp2p/py-libp2p/pull/175/files#diff-6c993f521171b6c76bee6f6d4158a91f, but need to more tests. 

#### Example
- Python
    - https://github.com/libp2p/py-libp2p/blob/master/libp2p/protocol_muxer/multiselect_client.py#L31
- Go
    - SelectProtoOrFail: https://github.com/multiformats/go-multistream/blob/277835d160f4821f43d57a5bc6322180e8f5e3c4/client.go#L21-L29
    - Delimited read/write: https://github.com/multiformats/go-multistream/blob/master/multistream.go#L75-L91

**Comment by ralexstokes** [comment]
Yep, this is part of what I mean in #216; let's make sure we are clear about what operations we need where
