### ISSUE TITLE
Ensure protocol negotiating process is correct

### ISSUE THREAD

**Issue by mhchia** [libp2p/py-libp2p#239]
In Go, the process of negotiation for connection upgrading is:
1. Negotiate multiselect protocol id.
2. Negotiate security level.
3. Negotiate multiselect protocol id.
4. Negotiate multiplexer.

In Python, some steps are wrong or missing. I've fixed the `TransportUpgrader` and made it work with Go in https://github.com/libp2p/py-libp2p/pull/175/files#diff-6c722cdc8acbbb2dec74dc5e7e04ac6d.

### To-Do
- [ ] Add the fix in https://github.com/libp2p/py-libp2p/pull/175 for both side(Python to Go and Go to Python).
- [ ] Add tests.

**Comment by ralexstokes** [comment]
Related: #242 .

**Comment by ralexstokes** [comment]
Related: #243.
