### ISSUE TITLE
Dep `coincurve` conflicts with Trinity

### ISSUE THREAD

**Issue by mhchia** [libp2p/py-libp2p#247]
Trinity requires [10.x.x](https://github.com/ethereum/trinity/blob/0d0c038499413812bee82cef0ea3d807e08fcf24/setup.py#L29), but we require [12.0.0](https://github.com/libp2p/py-libp2p/blob/master/setup.py#L41). Could we change to `10.x.x`?

Reference
- CI error in Trinity: https://circleci.com/gh/mhchia/trinity/5402?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by mhchia** [comment]
cc @ralexstokes

**Comment by pipermerriam** [comment]
@mhchia trace the dependency down and we can upgrade the dependency **if** we get all of our other libraries updated as well like `eth-key`

https://github.com/ethereum/eth-keys/blob/master/tox.ini

We're using a very old version for testing in `eth-keys` and it would be good to update that as well as expand what versions of coincurve we test against in CI.

**Comment by pipermerriam** [comment]
@mhchia see https://github.com/ethereum/eth-keys/pull/64 if you can review that for me I'll get it merged and released.

**Comment by mhchia** [comment]
Closed by #258
