### ISSUE TITLE
Rename `initiator` to `is_initiator`

### ISSUE THREAD

**Issue by mhchia** [libp2p/py-libp2p#255]
It is brought up in https://github.com/libp2p/py-libp2p/pull/253#discussion_r314989087. Throughout the codebase, we have a lot of `initiator` indicating whether a connection or a stream is the initiator. It will be more clear to be renamed to `is_initiator`. It will be great if we can also rename the other boolean-type flags when fixing this issue.

**Comment by ChihChengLiang** [comment]
Fixed in #332
