### ISSUE TITLE
Add tooling for docs, release, etc

### ISSUE THREAD

**Issue by carver** [libp2p/py-libp2p#294]
Want to be able to run `make release bump=minor` to trigger a release of the pip package, the docs build, etc.

**Comment by carver** [comment]
Feel free to assign to me.

**Comment by dmuhs** [comment]
I have had very good experiences with [bumpversion](https://pypi.org/project/bumpversion/). You supply it with some regex replacements, it automatically parses the version (format `{major}.{minor}.{patch}`), and bumps it automatically. You can configure it to automatically tag the branch and create a version bump commit as well. I use it to automatically bump the version, create all necessary commits and tags, and let my packages' CD pipeline handle all the publishing. With the tool installed, you simply type `bumpversion patch`, and `git push --tags && git push` and boom, there's the patch release.

An example `setup.cfg` with `bumpversion` enabled, and two regex replacements defined: https://github.com/dmuhs/mythx-cli/blob/master/setup.cfg#L1

**Comment by carver** [comment]
Yup, bumpversion is the utility we tend to use in my team's projects!

Check out how we do releases in Trinity:  https://trinity-client.readthedocs.io/en/latest/contributing.html#releasing

Relevant Makefile excerpt:
https://github.com/ethereum/trinity/blob/24213d8f22a03c370313d3a990eea6a2fe1e76e4/Makefile#L72-L84

My plan was to basically duplicate that approach, since I am offering to help with releases, and it's the workflow I prefer.

**Comment by mhchia** [comment]
Hey @carver , I just made a release https://github.com/libp2p/py-libp2p/releases/tag/v0.1.2 . Would you mind helping us to push the new package to PyPI?

> My plan was to basically duplicate that approach, since I am offering to help with releases, and it's the workflow I prefer.

Also, I opened https://github.com/libp2p/py-libp2p/issues/352 and was thinking it might probably be the time to have the release procedure discussed:). It will be great to have your PR for the plan you describe. I can also help to duplicate the approach if you don't have the bandwidth to handle it.

**Comment by carver** [comment]
Yup, I'll get it out today. FWIW, the tagged build is failing (though it's only a `lint` failure): https://travis-ci.com/libp2p/py-libp2p

I'll start adding the tooling and dogfood it to run the release, then open a PR.

**Comment by carver** [comment]
v0.1.2 is out: https://pypi.org/project/libp2p/#history

---

The goal is to have a release process very similar to: https://trinity-client.readthedocs.io/en/latest/contributing.html#releasing

I opened #353 with the first of the changes for release tooling.

I also asked the organization to approve access for readthedocs to hook in so that we can autobuild docs there.

**Comment by carver** [comment]
Releases are pretty smooth, now.
