### ISSUE TITLE
May I have write access?

### ISSUE THREAD

**Issue by carver** [libp2p/py-libp2p#295]
In order to do releases in a more automated way (which includes pushing tags to the upstream repo), I need to have write access. Can someone add me as a repo admin?

(I already am a maintainer on the pypi package)

Mostly relevant after #294

**Comment by mhchia** [comment]
Sorry I accidentally touch the close button. @raulk has the permission. I am asking him about this.🙏

**Comment by carver** [comment]
Thanks!
