### ISSUE TITLE
Pubsub is broadcasting block to the sender itself

### ISSUE THREAD

**Issue by ChihChengLiang** [libp2p/py-libp2p#329]
The version is the 0.1.1 from pypi. And this behavior is found in Trinity. Alice broadcasted a block and the block was received from gossip again. Logs here:

```
alice@16Uiu2HAmR	   DEBUG  2019-10-22 11:16:09,106             Validator  broadcasting block [signing_root]=5d1b..9f74, [hash_tree_root]=12fc..3a6a, slot=4, parent_root=d63a..aa52, state_root=42a9..538c, body=(randao_reveal=8a7f..4878, graffiti=0000..0000, proposer_slashings=(), attester_slashings=(), attestations=(<Attestation: ATTT a4f6..c426>,), deposits=(), voluntary_exits=(), transfers=()), signature=b973..a0eb
alice@16Uiu2HAmR	   DEBUG  2019-10-22 11:16:09,127      BCCReceiveServer  Received block over gossip. slot=4 signing_root=5d1b296de52600b50da40e8958022e4c6dce6b54904966395c593b447f059f74
alice@16Uiu2HAmR	   DEBUG  2019-10-22 11:16:09,128           BeaconChain  attempting import of block with slot 4 and signing_root 5d1b..9f74
```

**Comment by ralexstokes** [comment]
@mhchia assigned you -- let me know if you don't have bandwidth and i can take a look

@ChihChengLiang have you traced this bug to `py-libp2p`, it could be incorrect configuration in our use in `trinity`

**Comment by mhchia** [comment]
Is this related to the fact that a subscriber receives the data it just published? If yes, it should be a desired behavior...?

**Comment by ralexstokes** [comment]
this does seem to be what happens in `pubsub/pubsub.py` under `push_msg`'s call to `handle_talk`. i'm assuming this is part of the spec; i don't immediately see the reason to receive my own messages if i'm the original publisher.

this being said, if this is intended behavior, we should filter these blocks in the `trinity` code -- makes sense @mhchia @ChihChengLiang ?

**Comment by mhchia** [comment]
Yeah, it should be the intended behavior(at least Go implementation does it). We probably need to fix the issue in trinity.

**Comment by ChihChengLiang** [comment]
Here's what I found after looking into the codebase.
When calling `self.pubsub.publish(topic, data)` in Trinity, the pubsub should eventually ruled out the origin.

https://github.com/libp2p/py-libp2p/blob/477c08da968c4a4b09e81792994b30c89e57e74d/libp2p/pubsub/gossipsub.py#L175-L179

What might go wrong is the way the origin id is passed.

**Comment by ChihChengLiang** [comment]
Alright, sorry. Confirmed from @mhchia this is the intended behavior. See #65. Will fix that from Trinity side.

**Comment by mhchia** [comment]
[Link to the discussion](https://github.com/libp2p/go-libp2p-pubsub/issues/65) for future reference. Thanks to @ChihChengLiang for finding this discussion.

**Comment by ChihChengLiang** [comment]
Fixed in https://github.com/ethereum/trinity/pull/1232/
