### ISSUE TITLE
clean up type hints?

### ISSUE THREAD

**Issue by ralexstokes** [libp2p/py-libp2p#335]
small issue:

can we just keep one of these annotations? found it via an older version of `mypy` that marked it as redundant -- it is possible that we don't need both.

https://github.com/libp2p/py-libp2p/blob/f2bfc68f6dd99cf2c48dfd397eafb2bef57668f6/libp2p/stream_muxer/mplex/mplex_stream.py#L64-L65

**Comment by phayaran** [comment]
Raised PR #336  for this

**Comment by mhchia** [comment]
> can we just keep one of these annotations? found it via an older version of mypy that marked it as redundant -- it is possible that we don't need both.

Actually, I added one more since the later version mypy complains. Probably we can pin mypy to an older version if necessary.

**Comment by ralexstokes** [comment]
@mhchia gotcha -- i see the failure in https://travis-ci.com/libp2p/py-libp2p/jobs/249499439 from #336.

@phayaran welcome! thanks for the PR, but you can see from the CI failure that it is in fact required at the moment.

i'd think we want to use the latest version of `mypy` to get all the good stuff we can. so i'll close this for now.

feel free to re-open if we need to.
