### ISSUE TITLE
Parallelize tests

### ISSUE THREAD

**Issue by ralexstokes** [libp2p/py-libp2p#338]
I was working on doing some unrelated testing for a feature and tried to parallelize the tests w/ https://pypi.org/project/pytest-xdist/.

I didn't look very closely but it seems that this does not work out of the box w/ our setup.

**Comment by pipermerriam** [comment]
> I didn't look very closely but it seems that this does not work out of the box w/ our setup.

What wasn't working?

**Comment by ralexstokes** [comment]
thanks for following back up on this :)

i just re-ran `pytest-xdist` on `master` @ dcfeb3e3 and it seems to be working -- when i ran it earlier, it did something where it didn't even start the tests and now i just get two failures (seemingly something w/ tests where a port is already allocated).

i'll open a new issue to integrate `pytest-xdist` (fixing any failures surfaced along the way)
