### ISSUE TITLE
Full-feature `ping` implementation

### ISSUE THREAD

**Issue by ralexstokes** [libp2p/py-libp2p#344]
Reference: https://github.com/libp2p/py-libp2p/pull/315#pullrequestreview-309232342

We have the basic viable implementation of `ping`. We should add features like ~sharing our local view of our address and~ measuring RTTs to remote peers.

edit: i mixed up which features are in `ping` and which are in `identify`

**Comment by mystical-prog** [comment]
hey @dhuseby 
can I work on this issue ? there are some clarifications that I think we should discuss if this is assigned to me

**Comment by dhuseby** [comment]
Absolutely!! Take it!! 🚀

**Comment by mystical-prog** [comment]
> Absolutely!! Take it!! 🚀 

Actually @dhuseby it has been solved and PR merged, so you can close this issue now
