### ISSUE TITLE
Readme outdated (regarding requirements_dev.txt)

### ISSUE THREAD

**Issue by ShadowJonathan** [libp2p/py-libp2p#364]
The current readme.md document says this:

```sh
virtualenv -p python3.7 venv
. venv/bin/activate
pip3 install -r requirements_dev.txt
python setup.py develop
```

`requirements_dev.txt` does not exist anymore in the top directory, I assume `setup.py` is a replacement for this.

Shouldn't the readme be updated to say `pip install .[dev]` or similar?

**Comment by mhchia** [comment]
Yes, `README.md` should be updated. Thanks for your report. Would you mind having a PR for the fix? :)

**Comment by ShadowJonathan** [comment]
After I've found a way to make a venv work in WSL (or remote Linux) reliably on my local setup (see #363), but yes, I'm planning to do that

**Comment by mhchia** [comment]
That will be great. Thanks! IMO we can reference the installation and development guide similar to here: https://github.com/ethereum/eth-utils#ethereum-utils . I think @carver can give more useful inputs on the document than me. 🙏

**Comment by ShadowJonathan** [comment]
Looked over there, it does not have any notable additions to what I had in mind other than `-e`, which is "editable mode", something I had not seen before, but after looking it up proves to be an essential flag to add to the dev setup section of the readme.

After I've confirmed `pip install -e .[dev]` to be working (on a Linux install), I'll submit a PR with that amendment plus some note about developing on windows (again, #363)

**Comment by ShadowJonathan** [comment]
(whoops)

**Comment by carver** [comment]
Hi! I'm doing a merge against a project template that updates those instructions a bit. I think this is taken care of in my PR already: #366

**Comment by ShadowJonathan** [comment]
You're right, thanks for the heads-up!
