### ISSUE TITLE
Setting up a readthedocs webhook.

### ISSUE THREAD

**Issue by carver** [libp2p/py-libp2p#367]
## What was wrong?

We want https://py-libp2p.readthedocs.io/en/latest/ to build on every new commit to master. The webhook isn't set up.

## How can it be fixed?

There are several different paths here:
- An existing admin adds me as a repository admin so I can add the RTD webhook to the repository settings.
- An existing admin creates a RTD account, and sets up the integration from readthedocs.io.
- I create the webhook URI in RTD, and an existing admin adds that webhook in the repository settings.

**Comment by mhchia** [comment]
cc @raulk

**Comment by carver** [comment]
Right now, the docs look like this: https://py-libp2p.readthedocs.io/en/latest/
(I'm manually triggering builds)

The goal is to someday structure the docs like this: https://trinity-client.readthedocs.io/en/latest/

**Comment by carver** [comment]
I have some kind of limited settings available now, but still no `Webhooks` section in `Settings`. I just manually triggered the build, for v0.1.4.

**Comment by carver** [comment]
I got access now, thanks. The webhook is set up, so the `latest` docs rebuild on every commit to master. I also set up the docs site to default to stable ("stable" is the latest tagged build without an alpha/beta mark, which is currently v0.1.4).
