### ISSUE TITLE
Remove kademlia module

### ISSUE THREAD

**Issue by ChihChengLiang** [libp2p/py-libp2p#374]
## What was wrong?

Currently, Kademlia is a blocker for further development. Since it is not used in Eth2.0, we have minimized the maintenance of this module for a while. But it also created a vicious cycle that the less we maintain it, the harder we maintain it.

For example, it has no typing so adding new features could be difficult. For another, it's heavily based on asyncio, adding extra work to port libp2p to Trio.

I would suggest removing Kademlia first, and then rework a new one when the py-libp2p library has been rearchitected to some degree. Desirably when we have a sans-io version of py-libp2p.

### Concerns of removing Kademlia

- Some users might have already been using it.

## How can it be fixed?

Remove `libp2p/kademlia` and `tests/kademlia`

**Comment by mhchia** [comment]
Thanks for bring it up. Totally agree on it. The current `kademlia` module is not conforming to the go implementation. It uses standalone UDP transport instead of the abstracted transport in libp2p. It is reasonable, but it also makes `kademlia` unable to talk with the other libp2p implementations.

**Comment by ralexstokes** [comment]
i'd also support deprecation -- the code will remain in the git history so it will serve as a useful reference when we need to bring it back.
