### ISSUE TITLE
Uniform formatting format across library

### ISSUE THREAD

**Issue by ShadowJonathan** [libp2p/py-libp2p#382]
The current library uses a mix of `"" %`, `"%s".format` and `"{}".format` everywhere.

`"" %` formatting is heavily outdated (up for debate), alongside it being relatively un-pythonic.

Since python 3.6 (the current minimally supported version of this library), "f-strings" were introduced, this formalizes down from `"{}".format` into `f"{}"`:
```py
value = "supercalifragilisticexpialidocious"

# Percentage formatting with symbol
"%s" % value

# Percentage formatting with format call
"%s".format(value)

# Brace formatting with format call
"{0!s}".format(value)

# Brace formatting with f-string
f"{value!s}"
```

Even if f-strings would not be a good, viable or a desirable candidate, I at *least* am asking if there would be a *consistent* formatting style across the library. With a coding style document somewhere to note this down, and/or linters to enforce this (`flake8-pep3101` , `flake8-string-format`).

**Comment by pipermerriam** [comment]
Note that there are [good reasons](https://github.com/ethereum/snake-charmers-tactical-manual/issues/19#issuecomment-442616682) why logging statements should use `%s` style formatting.  :+1: to all of the others being consistent.  `f-strings` are the current standard we're using elsewhere.

**Comment by ShadowJonathan** [comment]
`flake-pep3101` still reports that there are modulo formatting operators used in some files, and if f-strings are the standard, it should be indicated in some coding style document somewhere, I'm still seeing some normal `.format` calls here and then.

**Comment by ShadowJonathan** [comment]
But I'll get started on checking and correcting formatting mistakes, I'm even going to make a linter that enforces f-strings to incorporate in this library (as I don't see any made specifically to make f-strings a norm in the files that it would check)

**Comment by mhchia** [comment]
After searching, we only have one `.format` here: https://github.com/libp2p/py-libp2p/blob/4b01c33d54d88c1d8e9e8e5247b0c97b1d45ab15/libp2p/host/basic_host.py#L96.

**Comment by ShadowJonathan** [comment]
So to summarize:

f-strings everywhere *except* for log entries, which use `%s`, correct?

**Comment by ShadowJonathan** [comment]
@pipermerriam 

Because if so, then I'm thinking of making another branch + draft PR that:
1. Changes everything to use f-strings (except logging)
2. Adds a styling document or a notation in `README.md` about this styling (and a note that clears up logging using `%s`)
3. Linters that check for this with black or flake8, specifically-created ones, if needed (which'll end upon pypi as a general package for everyone to use)

**Comment by pipermerriam** [comment]
:+1:  though I'd advocate to do the cleanup now and focus on the automated linting in a subsequent step.

**Comment by ralexstokes** [comment]
@ShadowJonathan do you feel like we can close this issue?
