### ISSUE TITLE
Want to easily know remote peers I am connected to

### ISSUE THREAD

**Issue by ralexstokes** [libp2p/py-libp2p#419]
The closest thing we have right now is the `PeerStore` which may be meant more for "peers i know about", regardless of current connection status.

The `PeerStore` also includes the local peer, which is not expected for the property referred to in this issue.

**Comment by ralexstokes** [comment]
Candidate: `Host.get_network().connections`

**Comment by mystical-prog** [comment]
hey @pacrob
can you please assign this issue to me ?

I propose to create a new method named `get_connected_peers` in `IHost` class

**Comment by mystical-prog** [comment]
@pacrob this issue can be marked closed because of #483
