### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by McSinyx** [libp2p/py-libp2p#427]
Hi, it seems that in the last few months, this project hasn't been given much attention.  Per a private discussion with @ShadowJonathan, I was informed that the project is not any longer active.  If that is really the case, I would like to offer a hand to warm things up a little to attract future contributor.  The codebase is not something I can maintain alone, given its size and my unfamiliarity with it, but I really don't want to see it being abandon after quite some money and effort being invested to make it somewhat useful.

**Comment by mhchia** [comment]
I think it's just people who worked on this project (including myself) getting busy with other stuff and no longer work on it. Personally, it's also nice for me to see py-libp2p keeps been developing. Do you have an idea in mind about how to move it forward?

**Comment by McSinyx** [comment]
Thanks, it's heartwarming to know hear that this is not abandoned.  I don't have any plan in mind in particular, just some housekeeping and start tackling some old issues.
