### ISSUE TITLE
No instructions for pubsub/gossipsub?

### ISSUE THREAD

**Issue by iljah** [libp2p/py-libp2p#430]
Running make html in docs didn't seem to produce any instructions on how to use pubsub/gossipsub. Are there examples/instructions somewhere, in repository or online?

**Comment by mhchia** [comment]
I'd suggest you have a look at the API [reference](https://py-libp2p.readthedocs.io/en/latest/libp2p.pubsub.html) and also [the test for pubsub](https://github.com/libp2p/py-libp2p/blob/master/tests/pubsub/test_pubsub.py).

**Comment by iljah** [comment]
I did, neither was very helpful. Gossipsub version of chat example should be informative enough...

**Comment by SwJay** [comment]
Glad to hear that the project is reactived now, is there any updates on some examples and instructions on Gossipsub or Pubsub? Really need it.

**Comment by pacrob** [comment]
Reactivated, yes! But not a ton of time to actually work on it. I'll take a look at this this weekend.

**Comment by kazzmir** [comment]
Updated references:
pubsub test:
https://github.com/libp2p/py-libp2p/blob/main/tests/core/pubsub/test_pubsub.py

gossipsubtest
https://github.com/libp2p/py-libp2p/blob/main/tests/core/pubsub/test_gossipsub.py

**Comment by SwJay** [comment]
Great! Thanks for the references.

**Comment by pacrob** [comment]
Closing as complete, please open a new issue if needed.
