### ISSUE TITLE
Updating python support to 3.8, getting dependencies updated

### ISSUE THREAD

**Issue by nloadholtes** [libp2p/py-libp2p#435]
## What was wrong?
Python3.6 reached of of life in December of 2021, and Python3.7 will reach end of life in June 2023. This commit changes the default Python to be 3.8 (end of life is Oct 2024) and updates enough of the dependencies to get the docs target to build correctly under tox.

Overall goal: Upgrade to python3.8, upgrade the minimal set of libraries to get tox checks to pass, only changes to the code are to get tox checks to pass.

Side note: I had trouble getting the interop tests to run (even with clean checkout of master branch). So for this PR, I commented them out of the `.travis.yml` file. The interop tests are important, and I would like to work on getting those working as a followup PR.

[PR to address this](https://github.com/libp2p/py-libp2p/pull/434)

**Comment by pacrob** [comment]
Closed by #447
