### ISSUE TITLE
Is this project abandoned

### ISSUE THREAD

**Issue by robertsdotpm** [libp2p/py-libp2p#438]
From looking at the commit messages it seems that only the cryptography dependencies have been updated (probably a third-party library anyway?) The roadmap seems to show no planned development for many features that would be useful for p2p networking.

I thought it would be good to have a solid peer-to-peer library for Python. So I built one from scratch. My library supports the following main features:

- Multiple interfaces
- IPv6 / IPv4 / TCP / UDP
- NAT enumeration of most behaviours to improve TCP hole punching success
- 4 techniques to establish P2P connections
- Built on open protocols: it uses STUN for address lookups, MQTT for signalling, and TURN for relaying
- Multiple fallback servers; multiple routes per peer in case a signalling server goes down
- Can be used as a Python package or from other languages using a REST API
- Windows, Mac OS X, FreeBSD, Linux, and Android
- Supports Python 3.5 or higher on non-windows, 3.6 or higher for windows

The Github for it is [here](https://github.com/robertsdotpm/p2pd) and the docs are [here](https://p2pd.net/)

**Comment by dhuseby** [comment]
I would like to help @pacrob get this project back out of the inactive list. @robertsdotpm, it would be great if you had some spare cycles to help us out. Keep an eye on the discussions in this repo for more to come. Reply here if you'd like to help.

**Comment by dhuseby** [comment]
It would be awesome to fold in some of your code to get py-libp2p caught up.

**Comment by dhuseby** [comment]
> In the past I've tried to help Protocol Labs with p2p networking. I applied to open roles on the Libp2p team where the excellent hiring manager failed me because he thought my Discord experience was lacking. I kid you not, your hiring manager failed me because 'part of the role was talking to the community on discord' which it seemed that for a networking engineer, I was lacking in.

Man that sucks. I'm sorry to hear that. 

> It seems that since Protocol Labs does not want my help they can do it without me.

Well, the good news is I don't work for Protocol Labs and the libp2p Project is now an independent open source project under the libp2p Foundation. The people working on and maintaining it do so because they care about it.

@pacrob and I are trying to revive this implementation of the libp2p specifications. We could use your help and I personally would like to get to know you better.

Thank you for your suggested fixes and example code. Is there any way you'd consider attending the next py-libp2p maintainers meeting on April 25th? Here's the event page for the meeting: https://lu.ma/2024-04-25-py-libp2p

**Comment by dhuseby** [comment]
@robertsdotpm with your help I think we could make py-libp2p actually useful. If you want to help with the code and are willing to show up to a meeting every month, I'd be happy to make you a maintainer of this project and support you in any way I can.

**Comment by pacrob** [comment]
@robertsdotpm I'm sorry you've had a bad experience. That does sound frustrating. I wish you all the best.

The conversation has moved away from what's helpful to py-libp2p itself, so I'll close the issue.

**Comment by dhuseby** [comment]
> They do not have a culture that encourages experts to participate and actively keep them out. Ironically, its these non-experts that are deferred to in such discussions from non-technical people. 

I don't work for Protocol Labs. Neither does @pacrob. I have been empowered to independently grow this community however I can. I'm personally inviting you to try again. I think you'll find things are different now that the libp2p community is independent.
