### ISSUE TITLE
Minimum libp2p requirements

### ISSUE THREAD

**Issue by carver** [libp2p/py-libp2p#58]
I just wanted to cross-link this post: https://github.com/ethresearch/p2p/issues/4#issuecomment-436702674

It appears to define the subset of libp2p features needed by eth2.0. I thought you might find it useful. My feelings won't be hurt if I'm wrong and you close this issue without explanation. :)

**Comment by robzajac** [comment]
That'll actually be quite useful to us! Thanks for posting.

@stuckinaboot @zixuanzh @alexh

**Comment by stuckinaboot** [comment]
This is mostly accurate except security module negotiation really should be in that list too.

**Comment by mhchia** [comment]
Should already be fixed?
