### ISSUE TITLE
Update read logic to support multiple streams over one connection

### ISSUE THREAD

**Issue by alexh** [libp2p/py-libp2p#86]
Read logic should be updated to support multiple streams over one connection. Current logic fails in the case I have streams open with A and B over one connection. A sends me a message then B sends me a message. I call read on my stream with B. Currently, we would pull off the message from A from the connection then the read call would fail.

This will be fixed by reading all available messages in handle_incoming.

**Comment by robzajac** [comment]
Resolved in #126.
