### ISSUE TITLE
Plan to generate doc use sphinx?

### ISSUE THREAD

**Issue by csunny** [libp2p/py-libp2p#90]
This lib hasn't document right now, if  is it a plan to use sphinx to generate document?

**Comment by Mikerah** [comment]
See this [issue](https://github.com/zixuanzh/py-libp2p/issues/35).

**Comment by zixuanzh** [comment]
@csunny it will be great if you can help us set it up with either sphinx or pydoc. All our classes and functions have docstring documentation. Thanks!
