### ISSUE TITLE
Why not use kademlia as a submodule?

### ISSUE THREAD

**Issue by csunny** [libp2p/py-libp2p#97]
Recently,  I want to use py-libp2p in my  [py-bitcorin](https://github.com/csunny/py-bitcoin) project,  and i notice this lib replace origin dht with kademlia project.  it is a better solution with git submodule, is it?

**Comment by robzajac** [comment]
That's a good point. We originally copied in the module so we could make changes to it. A better solution might be for us to make a fork of the Kad project and include it in py-libp2p as a Git submodule.

Truthfully, we haven't found a use for Kademlia yet in the existing py-libp2p feature set, so we'll investigate this further once we start to expand our implementation (most likely when doing peer discovery).

**Comment by magniff** [comment]
Why not use https://github.com/bmuller/kademlia implementation as a site-package? Just add it to the `install_requires` list, setuptools will autoinstall kademlia stuff with a proper versions as a dependency.

**Comment by alexh** [comment]
We will not be importing https://github.com/bmuller/kademlia as a side package because we need to make deep changes to his implementation to suite our needs
